cmake_minimum_required(VERSION 2.8)
set(ARM_PREFIX arm-frc-linux-gnueabi)

set(CMAKE_SYSTEM_NAME "Linux")
set(MY_SYSROOT $ENV{FRC})


set(CMAKE_C_COMPILER ${MY_SYSROOT}/bin/${ARM_PREFIX}-gcc.exe)
set(CMAKE_CXX_COMPILER ${MY_SYSROOT}/bin/${ARM_PREFIX}-g++.exe)

set(CMAKE_SHARED_LINKER_FLAGS "")
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
set(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
